[flyway]
locations = ["filesystem:migrations"]


[environments.default]
locations = ["filesystem:migrations"]
url = "jdbc:sqlserver://docgen.csxil53pu1c8.eu-west-1.rds.amazonaws.com:1433;authentication=sqlPassword;databaseName=DocGen;encrypt=true;trustServerCertificate=true"