name: Deploy DocGen GUI

on:
  push:
    branches:
      - main
    paths:
      - DocGenGUI/**

jobs:
  deployGUI:
    defaults:
      run:
        shell: pwsh
        working-directory: .\DocGenGUI

    runs-on: windows-latest

    env:
      APP_NAME: DocGen

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Publish to .exe
      run: dotnet publish -c Release --self-contained -p:PublishSingleFile=true 

    - name: Create Github Release
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: Release-${{ github.run_number }}
        artifacts: ${{ github.workspace }}\DocGenGUI\bin\Release\net6.0-windows\win-x64\publish\*.exe
        replacesArtifacts: true
        token: ${{ github.token }}
        commit: ${{ env.GITHUB_SHA }}
        allowUpdates: true