name: Deploy DocGen GUI

on:
  push:
    branches:
      - main
    paths:
      - DocGenGUI/**

jobs:
  deployGUI:
    defaults:
      run:
        shell: pwsh
        working-directory: .\DocGenGUI

    runs-on: windows-latest

    env:
      APP_NAME: DocGen

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Publish to .exe
      run: dotnet publish -c Release --self-contained -p:PublishSingleFile=true 

    - name: Zip files
      run: Compress-Archive .\bin\Release\net6.0-windows\win-x64\publish\ publish.zip

    - name: Create Github Release
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: Release-${{ github.run_number }}
        artifacts: ${{ github.workspace }}\DocGenGUI\*zip
        replacesArtifacts: true
        token: ${{ github.token }}
        commit: ${{ env.GITHUB_SHA }}
        allowUpdates: true

    - name: Download rel-monkey
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/Release-Monkey/release-monkey/releases/download/latest/rmk.exe" -OutFile "rel-monkey.exe"
    - name: Load Release Key
      run: ./rel-monkey load-release-key "${{ secrets.RELEASE_KEY }}"

    - name: Publish Release
      shell: pwsh
      run: ./rel-monkey create-release "Release-${{ github.run_number }}" "https://github.com/Release-Monkey/release-monkey/releases/tag/Release-${{ github.run_number }}"
