name: AWS-Infrastructure

on:
  push:
    branches:
      - tshego/feat/BGP-51-CICD

env:
  AWS_REGION: "eu-west-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  id-token: write
  contents: read

jobs:
    ConfigureAwsAndTerraform:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: infrastructure
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                    aws-region: ${{ env.AWS_REGION }}
                    aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                    audience: sts.amazonaws.com

            - name: Check out terraform
              uses: hashicorp/setup-terraform@v3
 
            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              id: plan
              run: terraform plan

            - name: Terraform Apply
              run: terraform apply -auto-approve

    build_and_create_Artifact:
      needs: ConfigureAwsAndTerraform
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: DocGenApi/DocGen.API
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
      
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 8.0.*
      
        - name: Install dependencies
          run: dotnet restore
      
        - name: Build
          run: dotnet build --configuration Release --no-restore
      
        - name: Test
          run: dotnet test --no-restore --verbosity normal

        - name: Publish
          run: dotnet publish DocGen/DocGenApi/DocGen.API/DocGen.API.csproj -c Release -o release — nologo
                 

